<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Tests\TestCase;

class PostTest extends TestCase
{
    use DatabaseMigrations;
    private $post;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->post = factory('App\Post')->create();
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testExample()
    {
        $this->assertTrue(true);
    }

    /** @test */
    public function a_post_has_a_creator()
    {
        $this->assertInstanceOf('App\User', $this->post->creator);
    }
}
